Improving error/warning messages in Json response to report submission
CDCgov/prime-data-hub pull request #1080
Opened 2021-05-13 20:23 UTC by tlosbo

When posting a report that has unexpected column headers or invalid/unexpected data, the messages provided in the Json response use internal field names that are confusing to the client posting the report. On missing fields, the message shows the CSV header but not the external/internal combination. After discussion on issue #1066 this format was decided:
`'<external field(s)>' ('<internal field>')`

## Changes
- added a custom getter to create the desired field mapping
- replaced the internal field name in all the messaging to the field mapping from the custom getter
- added a findElementByCsvName to the Schema class to find the Element and access the custom getter for missing fields

## Checklist
- [ ] review the errors and warnings by submitting bad data and confirm that they contain the desired information

### Testing
- [x] Tested locally?
- [ ] Ran `quickTest all`?
- [x] Ran `./prime test` against local Docker ReportStream container?
*** Tests FAILED:  garbage *** (known issue)
- [ ] Downloaded a file from `http://localhost:7071/api/download`?
- [ ] Added tests?

### Security
- [x] Did you check for sensitive data, and remove any? 
- [ ] Does logging contain sensitive data?  
- [ ] Are additional approvals needed for this change?
- [ ] Are there potential vulnerabilities or licensing issues with any new dependencies introduced?

### Process
- [x] Includes a summary of what a code reviewer should verify?
- [ ] Updated the release notes?
- [ ] Database changes are submitted as a separate PR?
- [ ] DevOps team has been notified if PR requires ops support?

## Security
*List potential security threats and mitigations in the PR*

## Fixes
*List GitHub issues this PR fixes*
- #1066

## To Be Done
*Create GitHub issues to track the work remaining, if any*

2021-05-17 15:13 UTC, MauriceReeves-usds approved these changes

2021-05-17 15:13 UTC, MauriceReeves-usds requested changes
The code changes look fine, but we should add some unit tests for this.

2021-05-18 12:42 UTC, jimduff-usds reviewed
Looks good - I thought your solution was simple and comprehensive.   I agree with Mo that a unit test on fieldMapping would be good.

Super-useful would be a new test in TestReportStream wherein we create "bad" data with a dummy schema that causes each one of the errors you have modified to occur.   But this is different than testing whether the messages are useful to humans or not.  I was so inspired by this idea, I wrote a ticket for it: #1113.

I do suspect there will be obscure cases where there are multiple CsvField values for a single element, that will look weird on errors.  But this feature has general problems anyway - for example, what would it mean for an element E in some _incoming_ data to be assoc with two csvfields "a" and "b" - and what if "a" is 10 and "b" 20?  What do we do with that?

2021-05-18 14:16 UTC, tlosbo commented
I'll address the unit test in issue #1113

2021-05-18 16:35 UTC, jimduff-usds approved these changes

2021-05-18 16:36 UTC, merged