CSV download page HTML & CSS
CDCgov/prime-data-hub pull request #129
Opened 2020-12-05 03:43 UTC by drew-usds

This PR does ...

## Changes
- Adds `/assets` dir to `/prime-router`
- Contains HTML & CSS (+USWDS) for the CSV download page

## Checklist
- [x] Tested locally?
- [x] Added new dependencies? _SORT OF ... added USWDS SCSS_
- [ ] Updated the docs?
- [x] Added a test? _N/A_
- [x] Did you check for sensitive data, and remove any?
- [x] Are additional approvals needed for this change?
- [x] Are there potential vulnerabilities or licensing issues with any new dependencies introduced?

## Fixes 

- Partially fixes #91 

## To Be Done

- Finish rest of checklists in #91

2020-12-07 18:06 UTC, RickHawesUSDS requested changes
Looks pretty heavy. 501 files. Lot's of fonts and other assets. Can we minify the template?

2020-12-08 21:32 UTC, drew-usds commented
Ah sorry didn't see this feedback earlier @RickHawesUSDS. This PR includes all of USWDS, which we need to build our final output files. I was thinking @mry-usds would only be using the final files (the index.html, the compressed css, select fonts/images/icons), but we'd still need the whole USWDS package here for future work/collaboration. Following up on this in Slack.

2020-12-09 15:36 UTC, dmethvin-gov commented
I think many of these files are actually build artifacts or dependencies that shouldn't be committed. Any `.css` files created from the `.scss` off USWDS for example should not be in the repo. The [developer instructions](https://designsystem.digital.gov/documentation/developers/) aren't super clear on this, or at least they weren't clear to me and further complicated because I was using React and Webpack. However, if this is a static page you should just be able to use the built CSS file and assets (fonts, icons, etc). Let me know if you want to pair on this and we can stumble through it together.

2020-12-09 16:47 UTC, RickHawesUSDS approved these changes

2020-12-10 17:35 UTC, merged