PA and STRAC onboarding using Redox
CDCgov/prime-data-hub pull request #228
Opened 2021-01-04 05:54 UTC by RickHawesUSDS

This PR adds the STRAC app sending to PA us

## Changes 
- 
- 

## Checklist
- [ ] Tested locally?
- [ ] Added new dependencies?
- [ ] Updated the docs?
- [ ] Added a test?
- [ ] Did you check for sensitive data, and remove any?
- [ ] Are additional approvals needed for this change?
- [ ] Are there potential vulnerabilities or licensing issues with any new dependencies introduced?

## Fixes 

- #issue

## To Be Done

- #issue

2021-01-04 06:31 UTC, RickHawesUSDS commented on .github/workflows/release.yml
> +
The REDOX secret is kept in KeyBase as well.

2021-01-04 06:31 UTC, RickHawesUSDS commented on prime-router/docker-compose.yml
> +        target: /config
This mock server emulates the Redox end-point.

2021-01-04 06:31 UTC, RickHawesUSDS commented on prime-router/metadata/organizations-local.yml
> -        format: CSV
Removing these test configs. Not needed.

2021-01-04 06:31 UTC, RickHawesUSDS commented on prime-router/metadata/organizations-prod.yml
>    - name: az-phd
STRAC has a new client and new schema.

2021-01-04 06:31 UTC, RickHawesUSDS commented on prime-router/metadata/organizations-prod.yml
> +#            apiKey: 9e7f9bd1-a876-4f10-9d17-0833dc7bf60d # Redox prod
The PROD version is not ready.

2021-01-04 06:31 UTC, RickHawesUSDS commented on prime-router/metadata/organizations-test.yml
> +        format: REDOX
CO is setup in staging.

2021-01-04 06:31 UTC, RickHawesUSDS commented on prime-router/metadata/schemas/covid-19.schema
>      documentation: Is the patient hospitalized?
Correct an error

2021-01-04 06:31 UTC, RickHawesUSDS commented on prime-router/metadata/schemas/covid-19.schema
Revised HHS guidance

2021-01-04 06:31 UTC, RickHawesUSDS commented on prime-router/metadata/schemas/covid-19.schema
>      natFlatFileField: Ordering_facility_county
Generally, removing cardinality ONE from elements of the main schema.

2021-01-04 06:31 UTC, RickHawesUSDS commented on prime-router/metadata/schemas/covid-19.schema
Another mistake in the HL7 schema.

2021-01-04 06:31 UTC, RickHawesUSDS commented on prime-router/metadata/schemas/covid-19.schema
> +
New element that is used by STRAC.

2021-01-04 06:31 UTC, RickHawesUSDS commented on prime-router/metadata/valuesets/covid-19.valuesets
>      - code: 95418-0
LONIC 2.69 is out.

2021-01-04 06:31 UTC, RickHawesUSDS commented on prime-router/metadata/valuesets/covid-19.valuesets
Missing part of the valueset.

2021-01-04 06:31 UTC, RickHawesUSDS commented on prime-router/pom.xml
>          <serialization.version>1.0.1</serialization.version>
This fixes a bug where `isEmpty` was marked as deprecated.

2021-01-04 06:31 UTC, RickHawesUSDS commented on prime-router/pom.xml
>          <dependency>
FUEL is a Kotlin based HTTP package.

2021-01-04 06:31 UTC, RickHawesUSDS commented on prime-router/src/main/kotlin/FakeReport.kt
> +                        } else {
Alt values for faker

2021-01-04 06:31 UTC, RickHawesUSDS commented on prime-router/src/main/kotlin/JurisdictionalFilters.kt
>          val values = args.subList(1, args.size)
pattern wasn't being used and the compiler warned about it.

2021-01-04 06:31 UTC, RickHawesUSDS commented on prime-router/src/main/kotlin/Mappers.kt
> +            when {
added a couple more cases to use.

2021-01-04 06:31 UTC, RickHawesUSDS commented on prime-router/src/main/kotlin/Report.kt
>              }
Moved to multi-pass algorithm to handle mappers with default values on input.

2021-01-04 06:31 UTC, RickHawesUSDS commented on prime-router/src/main/kotlin/Schema.kt
>      val baseName: String get() = formBaseName(name)
Useful for test cases.

2021-01-04 06:31 UTC, RickHawesUSDS commented on prime-router/src/main/kotlin/azure/Event.kt
>          val afterClause = if (at == null) "" else "$messageDelimiter${DateTimeFormatter.ISO_DATE_TIME.format(at)}"
Better name.

2021-01-04 06:31 UTC, RickHawesUSDS commented on prime-router/src/test/redox/initializerJson.json
> +[
This is the mock-server configured to look like Redox.

2021-01-04 12:56 UTC, jimduff-usds requested changes
Just noting these errors:

1. Unit test failed:  `[ERROR] gov.cdc.prime.router.TranslatorTests.test buildMapping  Time elapsed: 0 s  <<< FAILURE!
org.opentest4j.AssertionFailedError: expected: <true> but was: <false>
	at gov.cdc.prime.router.TranslatorTests.test buildMapping(TranslatorTests.kt:35)`
on this assertion:         ` assertEquals(true, oneToTwo.useDefault.contains("b"))`

2.  Unit test failed. 	at `gov.cdc.prime.router.SimpleReportTests.test producing az data from simplereport(SimpleReportTests.kt:100)`.  This is a test that tries to translate ./src/test/csv_test_files/input/simplereport.csv, to the az csv schema.   Errors:
- concat(Organization, Labname) failed - empty column in AZ data.  Expecting "Org1, Lab1"
- similarly, concat(Organization, ordering_facility_name) failed  - empty column in AZ data.  Expecting "Org1, Flat Plains"
- mapping from Result_ID column in simplereport.csv thru message_id -> placer_order_id -> testing_lab_specimen_id -> Specimen_ID column in AZ data is failing:  getting an empty column in AZ data.
- Test_code and Test_name column data empty in AZ data, expecting `94563-4` and `SARS-CoV-2 (COVID-19) Ag [Presence] in Respiratory specimen by Rapid immunoassay`, respectively.

3.   Formatting changes created during mvn build need to be checked in in Element.kt, Mappers.kt, etc.

NOTE:   ./quick-test.sh found the same csv schema generation problems as the above unit test, as well as a missing `Device_type` value in the Pima schema.

2021-01-05 00:54 UTC, RickHawesUSDS commented
@jimduff-usds 
The build works now and the `./quick_start.sh` tests pass. One issue that should continue to be discussed was caused by the `device_type` field that was created for PIMA. It maps one type to another type. Pretty sure this behavior is "wrong" in one sense or another, but I left it in.

2021-01-06 13:44 UTC, jimduff-usds approved these changes
Some minor comments.   
Let's merge in Mo's changes and I can re-test again.

2021-01-06 13:44 UTC, jimduff-usds commented on prime-router/src/main/kotlin/azure/DatabaseAccess.kt
> +            config.maxLifetime = 180000
I've been meaning to check whether there's a simple way to just have connections stay open "forever" when I'm running in the debugger locally.    Connections closing make the debugging more confusing, especially if you are trying to debug something database related!

2021-01-06 13:44 UTC, jimduff-usds commented on prime-router/src/main/kotlin/azure/DatabaseAccess.kt
>          txn: DataAccessTransaction,
Very glad to see the retry functionality!

2021-01-06 13:44 UTC, jimduff-usds commented on prime-router/src/main/kotlin/serializers/RedoxSerializer.kt
> +package gov.cdc.prime.router.serializers
I did a quick sanity check - Generate some redox json, and did a quick eyeball sanity check in a prettyprinter.   All looks good so far.

2021-01-06 21:05 UTC, merged