Jim/csvingest
CDCgov/prime-data-hub pull request #64
Opened 2020-11-13 21:28 UTC by jimduff-usds

This PR includes the csv ingest azure function.

## Changes
- Added two java files to impl ingest function, plus dependencies.

## Checklist
- [x] Tested locally?  (Also tested in prime-data-hub-router)
- [x] Added new dependencies?
- [ ] Updated the docs?
- [ ] Added a test?
- [x] Did you check for sensitive data, and remove any?
- [ ] Are additional approvals needed for this change?
- [ ] Are there potential vulnerabilities or licensing issues with any new dependencies introduced?

## Fixes 

- fix encoding-related HttpResponseException thrown when running in my resource group.

## To Be Done

- implement pseudo-rollback for failures in saving queue/container.
- tests
- move to kotlin

2020-11-14 18:54 UTC, mry-usds approved these changes

2020-11-16 00:13 UTC, RickHawesUSDS requested changes
Great to see this checking. I have some ideas. Could we talk before you merge?

2020-11-16 14:17 UTC, jimduff-usds commented on prime-router/src/main/kotlin/azure/#ProcessFunction.kt#
> +package gov.cdc.prime.router.azure
Yes, that's a mistake

2020-11-16 22:47 UTC, closed without merging

2020-11-16 22:48 UTC, jimduff-usds commented
This code got moved to Kotlin.  I'll submit a new PR.