Schema for Santa Clara, CA
CDCgov/prime-data-hub pull request #727
Opened 2021-03-29 01:32 UTC by RickHawesUSDS

This PR adds a schema for Santa Clara, CA.

## Changes
- SCC schema
- SCC org files

## Checklist
- [x] Tested locally?
- [x] Ran `quickTest all`?
- [ ] Ran `./prime test` against local Docker ReportStream container?
- [ ] Downloaded a file from http://localhost:7071/api/download
- [ ] Updated the release notes? 
- [ ] Added tests?
- [ ] Did you check for sensitive data, and remove any? 
- [ ] Does logging contain sensitive data?  
- [ ] Are additional approvals needed for this change?
- [ ] Are there potential vulnerabilities or licensing issues with any new dependencies introduced?

## Security
*List potential security threats and mitigations in the PR*

## Fixes
*List GitHub issues this PR fixes*
- #issue

## To Be Done
*Create GitHub issues to track the work remaining, if any*
- #issue

2021-03-29 13:35 UTC, MauriceReeves-usds requested changes
It would be good to add Santa Clara to `quick-test.sh` as part of this check in.

2021-03-29 13:35 UTC, MauriceReeves-usds commented on prime-router/metadata/schemas/covid-19.schema
> +    documentation: Assension number
Should be spelled `accession number`

2021-03-29 13:35 UTC, MauriceReeves-usds commented on prime-router/metadata/schemas/covid-19.schema
>    - name: specimen_description
We could add it to LIVD, but I don't think that the description is dependent on the type of device used like other fields are.

2021-03-29 13:35 UTC, MauriceReeves-usds commented on prime-router/metadata/schemas/CA/ca-scc-covid-19.schema
> +    default: ""
for the purposes of faking data, all elements should have a type defined, or you will encounter the error on line 170 in `FakeReport` about invalid element type.

2021-03-29 13:35 UTC, MauriceReeves-usds commented on prime-router/metadata/schemas/CA/ca-scc-covid-19.schema
> +      - name: "Patient Sex"
Are we passing through the text value or the code for this?

2021-03-29 13:35 UTC, MauriceReeves-usds commented on prime-router/metadata/schemas/CA/ca-scc-covid-19.schema
> +basedOn: "covid-19"
If we have a link for their schema it's good to put the `referenceUrl` at the top.

2021-03-29 13:35 UTC, MauriceReeves-usds commented on prime-router/metadata/schemas/CA/ca-scc-covid-19.schema
> +      - name: "OK to Contact Patient"
Needs a type if we're going to run it through the faker

2021-03-30 05:17 UTC, RickHawesUSDS commented
@MauriceReeves-usds Thanks for the suggestions. Improvements made.

2021-03-30 14:44 UTC, RickHawesUSDS commented on prime-router/metadata/schemas/covid-19.schema
> +    documentation: Assension number
Fixed

2021-03-30 17:33 UTC, MauriceReeves-usds approved these changes

2021-03-30 17:40 UTC, merged